title: RPA and two somking barrels
author: pab_blue
email: pab_blue@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A corrosive view on RPA today through its major contributions.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
